### PR TITLE
Bring Qt6 compatibility

### PR DESCRIPTION
**Pull request by nicogodet**
- Fix enums
- Remove calls to `exec_` and use `exec`
- Use `setChecked` instead of `setCheckState`: 
    - `setChecked` takes boolean which is type used in settings while `setCheckState` requires `Qt.Checkstate` enum
    - Tristate is not needed so no needs for `setCheckState`, `setChecked` can be safely used
- Add `supportsQt6` flag in metadata.txt so plugin can be installed in QGIS Qt6

Tested on qgis-qt6-dev from OSGeo4W:

- Tested to open config dialog
- Add project (file based only)
- Open layer from added menu
- Open help page

Animation9

<details>
  <summary>QGIS About</summary>
  
<table width='100%' align='center'><tr><td>Version de QGIS</td><td>3.41.0-Master</td></tr><tr><td>Révision du code</td><td><a href="https://github.com/qgis/QGIS/commit/d1de2574de">d1de2574de</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Version de Qt</td><td>6.6.3</td></tr><tr><td>Version de Python</td><td>3.12.7</td></tr><tr><td>Version de GDAL/OGR</td><td>3.11.0dev-d511807003 (Compiled)<br/>3.11.0dev-acdb4bdf68 (Running)</td></tr><tr><td>Version de Proj</td><td>9.5.0</td></tr><tr><td>Version de la base de données du registre EPSG</td><td>v11.016 (2024-08-31)</td></tr><tr><td>Version de GEOS</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>Version de SQLite</td><td>3.46.1</td></tr><tr><td>Version de PDAL</td><td>2.8.1</td></tr><tr><td>Version du client PostgreSQL</td><td>16.2</td></tr><tr><td>Version de SpatiaLite</td><td>5.1.0</td></td></tr><tr><td>Version de QWT</td><td>6.3.0</td></tr><tr><td>Version de QScintilla2</td><td>2.14.1</td></tr><tr><td>Version de l'OS</td><td>Windows 10 Version 22H2</td></tr><tr><td colspan="2"><i>Cette copie de QGIS dispose d'une sortie de débogage.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Extensions Python actives</b></td></tr><tr><td>french_locator_filter</td><td>1.1.1</td></tr><tr><td>menu_from_project</td><td>2.3.0-DEV</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>profiletool</td><td>4.3.0</td></tr><tr><td>swiss_locator</td><td>4.0.0</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>
  
</details>

### CODE REVIEW

**Comment by Guts** [comment]
Thanks for this work. 
Not sure it's complete but it's a good move.

Can you add a CI workflow to test against QGIS with Qt6 please?

**Comment by nicogodet** [comment]
No QGIS Qt6 docker image to my knowledge, go jump in the lake! 😄

**Review by Guts — APPROVED** [review]
Thanks @nicogodet for the work. 

I did not test on my side on Qt6 but I've tested on QGIS 3.34 with Qt5 and it does not break nothing.

Any though @jmkerloch?

**Comment by jmkerloch** [comment]
@Guts for me since this didn't break anything on Qt5 I am for a merge now.
This is only minors update there should not be any side effect.

**Pull request merged**
