### PR TITLE
Japanese translation is available.

### PR DESCRIPTION
**Pull request by Tokimasasogo**

### CODE REVIEW

**Comment by xcaeag** [comment]
thank you

**Comment by xcaeag** [comment]
The plugin is published (a first draft was not good).. you can test it.

Thank you for your participation,

Regards,

xavier

**Comment by yamamoto-ryuzo** [comment]
Tokimasasogo is a second-year university student (Information Science) who is currently doing an internship with me.
This is his first experience working as a translator, so I think it was a good stimulus for him.
He will be here until tomorrow so it will be a good experience for him to be able to test.
I will test tomorrow and tell him to contact you again.
Thank you very much.

**Comment by Tokimasasogo** [comment]
It worked fine. Thank you very much.

**Comment by xcaeag** [comment]
Glad to know the plugin used so far !
and long live free software.

**Comment by xcaeag** [comment]
And if you have a little time, other interesting plugins are to be translated!

- https://plugins.qgis.org/plugins/mask/
- https://plugins.qgis.org/plugins/nominatim/

**Comment by yamamoto-ryuzo** [comment]
QGIS has so many plug-ins that I don't know what to do.
Please wait for a while as we are asking for Japanese version sequentially as we confirm how to use it in our business.
Thank you very much.

**Pull request merged**
